version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees: ["johnlettman"]
    reviewers: ["johnlettman"]
    open-pull-requests-limit: 2
    commit-message:
      # Skip CI when updating, well, CI.
      # See: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
      prefix: '[skip ci] '
    schedule:
      timezone: "10:00 EST"
      interval: "daily"
