on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup check-sieve
      run: sudo snap install --edge check-sieve

    - name: Check sieve scripts
      run: ./check.sh

    - name: Output folder listing
      run: ./folders.sh
